import { existsSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import { Prisma, PrismaClient } from "../../generated/prisma";
import { ensureVariantCodes } from "../../lib/product-codes";

/**
 * Import a split index, one group, or a legacy JSON seed generated by
 * build_startech_full_seed.py.
 *
 * It upserts:
 * - Category (parent + child)
 * - Brand
 * - Product
 * - ProductVariant
 * - ProductVariantOption + ProductVariantOptionValue
 * - ProductSpecificationGroup + ProductSpecificationItem
 * - StockLevel in a default warehouse
 * - BARCODE + QRCODE through the project's existing ensureVariantCodes helper
 *
 * Run from repository root:
 *   npm run seed:startech
 */

const prisma = new PrismaClient();

// Reuse important categories that already exist in the current storefront seed.
// The source image folders use Deshi Plus-oriented slugs, while the application
// already has a few canonical slugs used by search / PC Builder / navigation.
const CATEGORY_SLUG_ALIASES: Record<string, string> = {
  component: "components",
  "ram-desktop": "desktop-ram",
  casing: "pc-case",
  desktop: "desktop-pc",
  gadget: "smart-gadget",
  camera: "cameras",
  "television-shop": "television",
  appliance: "home-appliance",
  "server-networking": "servers",
  "security-camera": "security",
  "accessories-headphone": "headphone-headsets",
  "hubs-docks": "docking-station",
};

const CATEGORY_NAME_ALIASES: Record<string, string> = {
  component: "Components",
  "ram-desktop": "Desktop RAM",
  casing: "PC Casing",
  desktop: "Desktop PC",
  gadget: "Gadgets",
  camera: "Cameras",
  "television-shop": "TV & Sound",
  appliance: "Appliance",
  "server-networking": "Servers",
  "security-camera": "Security",
  "accessories-headphone": "Headphone & Headsets",
  "hubs-docks": "Docking Station",
};

type SeedCategory = {
  name: string;
  slug: string;
  parentSlug: string | null;
  image: string | null;
  isActive: boolean;
  sortOrder: number;
  showInHeader: boolean;
  showInFooter: boolean;
  featured: boolean;
};

type SeedVariantOption = {
  name: string;
  position: number;
  values: Array<{ value: string; position: number }>;
};

type SeedSpecificationGroup = {
  name: string;
  position: number;
  items: Array<{ label: string; value: string; position: number }>;
};

type SeedVariant = {
  sku: string;
  price: number;
  currency: string;
  stock: number;
  options: Record<string, string>;
  isDefault: boolean;
  active: boolean;
  lowStockThreshold: number;
  costPrice: number | null;
  colorImage: string | null;
};

type SeedProduct = {
  unmatched?: boolean;
  name: string;
  slug: string;
  type?: "PHYSICAL" | "DIGITAL" | "SERVICE" | "BUNDLE";
  sku: string;
  categorySlug: string;
  brandName: string | null;
  description: string;
  shortDesc: string | null;
  model: string | null;
  warranty: string | null;
  basePrice: number;
  originalPrice: number | null;
  currency: string;
  weight: number | null;
  dimensions: Record<string, unknown> | null;
  available: boolean;
  featured: boolean;
  image: string;
  gallery: string[];
  soldCount?: number;
  ratingAvg?: number;
  ratingCount?: number;
  lowStockThreshold?: number;
  inventoryItemClass?: "CONSUMABLE" | "PERMANENT";
  requiresAssetTag?: boolean;
  bundleStockLimit?: number | null;
  stock: number;
  variants: SeedVariant[];
  variantOptions: SeedVariantOption[];
  specificationGroups: SeedSpecificationGroup[];
};

type SeedBrand = { name: string; slug: string; logo?: string | null };

type SeedFile = {
  schemaVersion: number;
  categories: SeedCategory[];
  brands?: SeedBrand[];
  products: SeedProduct[];
};

function slugify(value: string) {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/&/g, " and ")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "unknown"
  );
}

function readSeed(file: string): SeedFile {
  const path = resolve(process.cwd(), file);
  const parsed = JSON.parse(readFileSync(path, "utf8")) as SeedFile;
  if (!Array.isArray(parsed.categories) || !Array.isArray(parsed.products)) {
    throw new Error(`Invalid seed file: ${path}`);
  }
  return parsed;
}

type UnmatchedRecord = {
  stem: string;
  sourceImages: string[];
  sourceHierarchy: Array<{
    categorySlug: string;
    categoryName: string;
    subcategorySlug?: string | null;
    subcategoryName?: string | null;
    folderBrandName?: string | null;
  }>;
};

function appendUnmatched(file: string, seed: SeedFile, knownSlugs: Set<string>) {
  const unmatchedCandidates = [
    file.replace(/\.json$/i, ".unmatched.json"),
    file.replace(/\.json$/i, "unmatched.json"),
  ];
  const unmatchedFile = unmatchedCandidates.find((candidate) => existsSync(candidate));
  if (!unmatchedFile) return;
  const records: UnmatchedRecord[] = JSON.parse(readFileSync(unmatchedFile, "utf8"));
  if (!Array.isArray(records)) throw new Error(`Invalid unmatched file: ${unmatchedFile}`);
  let added = 0;
  for (const record of records) {
    const hierarchy = record.sourceHierarchy?.[0];
    if (!record.stem || !hierarchy?.categorySlug || !record.sourceImages?.length) {
      throw new Error(`Incomplete unmatched record in ${unmatchedFile}: ${record.stem}`);
    }
    const slug = slugify(record.stem);
    // Matched products always take precedence, including those in later groups.
    if (knownSlugs.has(slug)) continue;
    knownSlugs.add(slug);
    const addCategory = (categorySlug: string, name: string, parentSlug: string | null) => {
      if (seed.categories.some((category) => category.slug === categorySlug)) return;
      seed.categories.push({
        slug: categorySlug, name, parentSlug, image: null, isActive: true,
        sortOrder: seed.categories.length, showInHeader: false,
        showInFooter: false, featured: false,
      });
    };
    addCategory(hierarchy.categorySlug, hierarchy.categoryName, null);
    const categorySlug = hierarchy.subcategorySlug || hierarchy.categorySlug;
    if (categorySlug !== hierarchy.categorySlug) {
      addCategory(categorySlug, hierarchy.subcategoryName || categorySlug, hierarchy.categorySlug);
    }
    // Stable identity across reruns; no rejected search candidate is trusted.
    const sku = `STARTECH-UNMATCHED-${createHash("sha256").update(slug).digest("hex").slice(0, 24)}`;
    seed.products.push({
      unmatched: true,
      name: record.stem.replace(/[-_]+/g, " "), slug, sku, categorySlug,
      brandName: hierarchy.folderBrandName || null,
      description: "", shortDesc: null, model: null, warranty: null,
      // Required numeric fields use zero until an administrator supplies prices
      // and inventory. These incomplete products and variants cannot be sold.
      basePrice: 0, originalPrice: null, currency: "BDT", weight: null,
      dimensions: null, available: false, featured: false,
      image: record.sourceImages[0], gallery: [...new Set(record.sourceImages.slice(1))],
      stock: 0, variants: [], variantOptions: [], specificationGroups: [],
    });
    added += 1;
  }
  console.log(`${unmatchedFile}: ${added} unmatched products included, ${records.length - added} duplicates skipped`);
}

async function ensureWarehouse() {
  const existing = await prisma.warehouse.findFirst({
    orderBy: [{ isDefault: "desc" }, { id: "asc" }],
    select: { id: true },
  });
  if (existing) return existing;

  return prisma.warehouse.create({
    data: {
      code: "WH-HQ",
      name: "Head Office Central Warehouse",
      isDefault: true,
      country: "BD",
      division: "Dhaka",
      district: "Dhaka",
      area: "Head Office",
      address: {
        line1: "Head Office Central Warehouse",
        city: "Dhaka",
        country: "Bangladesh",
      },
    },
    select: { id: true },
  });
}

async function upsertBrand(name: string | null, cache: Map<string, number>) {
  const clean = name?.trim();
  if (!clean) return null;
  const key = slugify(clean);
  if (cache.has(key)) return cache.get(key)!;

  const byName = await prisma.brand.findUnique({
    where: { name: clean },
    select: { id: true },
  });
  if (byName) {
    await prisma.brand.update({
      where: { id: byName.id },
      data: { deleted: false },
    });
    cache.set(key, byName.id);
    return byName.id;
  }

  const bySlug = await prisma.brand.findUnique({
    where: { slug: key },
    select: { id: true, name: true },
  });
  if (bySlug) {
    await prisma.brand.update({
      where: { id: bySlug.id },
      data: { deleted: false },
    });
    cache.set(key, bySlug.id);
    return bySlug.id;
  }

  const record = await prisma.brand.create({
    data: { name: clean, slug: key, deleted: false },
    select: { id: true },
  });
  cache.set(key, record.id);
  return record.id;
}

async function syncVariantOptions(
  tx: Prisma.TransactionClient,
  productId: number,
  options: SeedVariantOption[],
) {
  const keepNames = options.map((x) => x.name);

  for (const optionSeed of options) {
    const option = await tx.productVariantOption.upsert({
      where: { productId_name: { productId, name: optionSeed.name } },
      update: { position: optionSeed.position },
      create: {
        productId,
        name: optionSeed.name,
        position: optionSeed.position,
      },
      select: { id: true },
    });

    const keepValues = optionSeed.values.map((x) => x.value);
    for (const valueSeed of optionSeed.values) {
      await tx.productVariantOptionValue.upsert({
        where: {
          optionId_value: { optionId: option.id, value: valueSeed.value },
        },
        update: { position: valueSeed.position },
        create: {
          optionId: option.id,
          value: valueSeed.value,
          position: valueSeed.position,
        },
      });
    }
    await tx.productVariantOptionValue.deleteMany({
      where: {
        optionId: option.id,
        ...(keepValues.length ? { value: { notIn: keepValues } } : {}),
      },
    });
  }

  if (keepNames.length) {
    const stale = await tx.productVariantOption.findMany({
      where: { productId, name: { notIn: keepNames } },
      select: { id: true },
    });
    const staleIds = stale.map((x) => x.id);
    if (staleIds.length) {
      await tx.productVariantOptionValue.deleteMany({
        where: { optionId: { in: staleIds } },
      });
      await tx.productVariantOption.deleteMany({
        where: { id: { in: staleIds } },
      });
    }
  } else {
    const stale = await tx.productVariantOption.findMany({
      where: { productId },
      select: { id: true },
    });
    const staleIds = stale.map((x) => x.id);
    if (staleIds.length) {
      await tx.productVariantOptionValue.deleteMany({
        where: { optionId: { in: staleIds } },
      });
      await tx.productVariantOption.deleteMany({
        where: { id: { in: staleIds } },
      });
    }
  }
}

async function syncSpecificationGroups(
  tx: Prisma.TransactionClient,
  productId: number,
  groups: SeedSpecificationGroup[],
) {
  // ProductSpecificationItem has onDelete Cascade from group, so replacing
  // groups is the safest idempotent way to remove stale vendor specifications.
  await tx.productSpecificationGroup.deleteMany({ where: { productId } });

  for (const group of groups) {
    await tx.productSpecificationGroup.create({
      data: {
        productId,
        name: group.name,
        position: group.position,
        items: {
          create: group.items.map((item) => ({
            label: item.label,
            value: item.value,
            position: item.position,
          })),
        },
      },
    });
  }
}

type SeedReport = {
  productIds: Set<number>;
  categoryIds: Set<number>;
  skippedProducts: number;
};

async function seedFile(seed: SeedFile, report: SeedReport) {
  const warehouse = await ensureWarehouse();
  const categoryIds = new Map<string, number>();
  const brandIds = new Map<string, number>();

  console.log(`Importing ${seed.categories.length} categories...`);
  const categoryActualSlugs = new Map<string, string>();

  for (const category of seed.categories) {
    const parentId = category.parentSlug
      ? categoryIds.get(category.parentSlug)
      : null;
    if (category.parentSlug && !parentId) {
      throw new Error(
        `Category parent must appear before child: ${category.slug} -> ${category.parentSlug}`,
      );
    }

    const parentActualSlug = category.parentSlug
      ? categoryActualSlugs.get(category.parentSlug)
      : null;
    let desiredSlug = CATEGORY_SLUG_ALIASES[category.slug] ?? category.slug;
    let existing = await prisma.category.findUnique({
      where: { slug: desiredSlug },
      select: { id: true, name: true, slug: true, parentId: true },
    });

    // Category.slug is globally unique. If a source child slug already exists
    // under a different parent (for example a similarly named category in the
    // old storefront), do not re-parent it. Create/reuse a parent-prefixed slug.
    if (existing && existing.parentId !== (parentId ?? null)) {
      if (!parentActualSlug && parentId) {
        throw new Error(
          `Could not resolve actual parent slug for ${category.slug}`,
        );
      }
      desiredSlug = parentId
        ? `${parentActualSlug}-${category.slug}`
        : `${category.slug}-startech`;
      existing = await prisma.category.findUnique({
        where: { slug: desiredSlug },
        select: { id: true, name: true, slug: true, parentId: true },
      });
    }

    const aliasedExisting =
      existing &&
      desiredSlug !== category.slug &&
      CATEGORY_SLUG_ALIASES[category.slug] === desiredSlug;

    const data = {
      name: aliasedExisting
        ? existing!.name
        : (CATEGORY_NAME_ALIASES[category.slug] ?? category.name),
      image: category.image,
      parentId: parentId ?? null,
      isActive: category.isActive,
      sortOrder: category.sortOrder,
      showInHeader: category.showInHeader,
      showInFooter: category.showInFooter,
      featured: category.featured,
      deleted: false,
    };

    const record = existing
      ? await prisma.category.update({
          where: { id: existing.id },
          data,
          select: { id: true, slug: true },
        })
      : await prisma.category.create({
          data: { ...data, slug: desiredSlug },
          select: { id: true, slug: true },
        });

    // Map SOURCE slug -> DB id so products do not care whether the database
    // uses an alias such as ram-desktop -> desktop-ram.
    categoryIds.set(category.slug, record.id);
    categoryActualSlugs.set(category.slug, record.slug);
    report.categoryIds.add(record.id);
  }

  for (const brand of seed.brands ?? []) {
    const key = slugify(brand.slug || brand.name);
    const existing = await prisma.brand.findFirst({
      where: { OR: [{ slug: key }, { name: brand.name }] },
      select: { id: true },
    });
    const record = existing
      ? await prisma.brand.update({
          where: { id: existing.id },
          data: {
            name: brand.name,
            slug: key,
            logo: brand.logo ?? null,
            deleted: false,
          },
          select: { id: true },
        })
      : await prisma.brand.create({
          data: {
            name: brand.name,
            slug: key,
            logo: brand.logo ?? null,
            deleted: false,
          },
          select: { id: true },
        });
    brandIds.set(key, record.id);
  }

  let index = 0;
  let seededProducts = 0;
  let skippedProducts = 0;
  for (const item of seed.products) {
    index += 1;
    if (item.unmatched) {
      const existing = await prisma.product.findFirst({
        where: { OR: [{ slug: item.slug }, { sku: item.sku }] },
        select: { id: true, sku: true, variants: { select: { id: true }, take: 1 } },
      });
      // Do not replace an existing catalog product with incomplete source data.
      // Retry our own placeholders so an interrupted variant import can finish.
      if (existing && (existing.sku !== item.sku || existing.variants.length > 0)) {
        skippedProducts += 1;
        report.skippedProducts += 1;
        console.log(`[${index}/${seed.products.length}] Preserved existing ${item.slug}`);
        continue;
      }
    }
    const categoryId = categoryIds.get(item.categorySlug);
    if (!categoryId) throw new Error(`Missing category: ${item.categorySlug}`);
    const brandId = await upsertBrand(item.brandName, brandIds);

    const existingBySlug = await prisma.product.findUnique({
      where: { slug: item.slug },
      select: { id: true, slug: true, sku: true },
    });
    const existingBySku = item.sku
      ? await prisma.product.findUnique({
          where: { sku: item.sku },
          select: { id: true, slug: true, sku: true },
        })
      : null;

    if (
      existingBySlug &&
      existingBySku &&
      existingBySlug.id !== existingBySku.id
    ) {
      throw new Error(
        `Product identity conflict for ${item.name}: slug belongs to product ${existingBySlug.id}, SKU belongs to product ${existingBySku.id}`,
      );
    }

    const existingProduct = existingBySlug ?? existingBySku;
    const productData = {
      name: item.name,
      sku: item.sku,
      type: item.type ?? ("PHYSICAL" as const),
      categoryId,
      brandId,
      description: item.description,
      shortDesc: item.shortDesc?.trim() || null,
      model: item.model?.trim() || null,
      warranty: item.warranty?.trim() || null,
      basePrice: item.basePrice,
      originalPrice: item.originalPrice,
      currency: item.currency || "BDT",
      weight: item.weight,
      dimensions:
        item.dimensions == null
          ? Prisma.JsonNull
          : (item.dimensions as Prisma.InputJsonValue),
      available: item.available,
      featured: item.featured,
      image: item.image,
      gallery: item.gallery ?? [],
      soldCount: item.soldCount ?? 0,
      ratingAvg: item.ratingAvg ?? 0,
      ratingCount: item.ratingCount ?? 0,
      deleted: false,
      lowStockThreshold: item.lowStockThreshold ?? 10,
      inventoryItemClass: item.inventoryItemClass ?? ("CONSUMABLE" as const),
      requiresAssetTag: item.requiresAssetTag ?? false,
      bundleStockLimit: item.bundleStockLimit ?? null,
    };

    const product = existingProduct
      ? await prisma.product.update({
          where: { id: existingProduct.id },
          // If SKU matched an existing product whose slug differs, preserve its
          // public slug instead of breaking existing links.
          data: {
            ...productData,
            ...(existingBySlug ? { slug: item.slug } : {}),
          },
          select: { id: true },
        })
      : await prisma.product.create({
          data: { ...productData, slug: item.slug },
          select: { id: true },
        });

    await prisma.$transaction(async (tx) => {
      await syncVariantOptions(tx, product.id, item.variantOptions ?? []);
      await syncSpecificationGroups(
        tx,
        product.id,
        item.specificationGroups ?? [],
      );

      const variantSeeds = item.variants?.length
        ? item.variants
        : [
            {
              sku: item.sku,
              price: item.basePrice,
              currency: item.currency || "BDT",
              stock: item.stock ?? 0,
              options: {},
              isDefault: true,
              active: item.available,
              lowStockThreshold: item.lowStockThreshold ?? 10,
              costPrice: null,
              colorImage: null,
            },
          ];

      const keepVariantIds: number[] = [];
      for (const variantSeed of variantSeeds) {
        const existing = await tx.productVariant.findFirst({
          where: { productId: product.id, sku: variantSeed.sku },
          select: { id: true },
        });
        const data = {
          productId: product.id,
          sku: variantSeed.sku,
          price: variantSeed.price,
          currency: variantSeed.currency || item.currency || "BDT",
          stock: variantSeed.stock,
          options: variantSeed.options as Prisma.InputJsonValue,
          colorImage: variantSeed.colorImage?.trim() || null,
          isDefault: variantSeed.isDefault ?? false,
          active: variantSeed.active ?? item.available,
          lowStockThreshold:
            variantSeed.lowStockThreshold ?? item.lowStockThreshold ?? 10,
          costPrice: variantSeed.costPrice,
        };

        const variant = existing
          ? await tx.productVariant.update({ where: { id: existing.id }, data })
          : await tx.productVariant.create({ data });
        keepVariantIds.push(variant.id);

        await tx.stockLevel.upsert({
          where: {
            warehouseId_productVariantId: {
              warehouseId: warehouse.id,
              productVariantId: variant.id,
            },
          },
          update: { quantity: variantSeed.stock },
          create: {
            warehouseId: warehouse.id,
            productVariantId: variant.id,
            quantity: variantSeed.stock,
            reserved: 0,
          },
        });

        await ensureVariantCodes(tx, {
          productId: product.id,
          variantId: variant.id,
        });
      }

      // Do not delete old variants automatically because they can be referenced
      // by orders. Mark stale variants inactive instead.
      if (keepVariantIds.length) {
        await tx.productVariant.updateMany({
          where: { productId: product.id, id: { notIn: keepVariantIds } },
          data: { active: false, isDefault: false },
        });
      }
    });

    seededProducts += 1;
    report.productIds.add(product.id);
    console.log(`[${index}/${seed.products.length}] Seeded ${item.name}`);
  }

  console.log(
    `\nGroup done. Categories=${new Set(categoryIds.values()).size}, Products seeded=${seededProducts}, Products skipped=${skippedProducts}, Brands=${brandIds.size}`,
  );
}

async function main() {
  const startedAt = performance.now();
  const report: SeedReport = {
    productIds: new Set<number>(),
    categoryIds: new Set<number>(),
    skippedProducts: 0,
  };
  const path = resolve(process.argv[2] || "prisma/startech-seed/index.json");
  const files = seedPaths(path);
  const seeds = files.map((file) => ({ file, seed: readSeed(file) }));
  const knownSlugs = new Set(seeds.flatMap(({ seed }) => seed.products.map((product) => product.slug)));
  for (const { file, seed } of seeds) appendUnmatched(file, seed, knownSlugs);
  console.log(`Importing ${seeds.length} groups, ${seeds.reduce((count, { seed }) => count + seed.products.length, 0)} products (including unmatched)`);
  for (const { file, seed } of seeds) {
    console.log(`Importing ${file}`);
    await seedFile(seed, report);
  }
  const elapsedSeconds = Math.floor((performance.now() - startedAt) / 1000);
  const hours = Math.floor(elapsedSeconds / 3600);
  const minutes = Math.floor((elapsedSeconds % 3600) / 60);
  const seconds = elapsedSeconds % 60;
  console.log([
    "\nStartech seed completed successfully",
    `Groups completed: ${seeds.length}`,
    `Products seeded (unique, created or updated): ${report.productIds.size}`,
    `Categories seeded (unique, created or updated): ${report.categoryIds.size}`,
    `Existing products preserved/skipped: ${report.skippedProducts}`,
    `Time taken: ${hours}h ${minutes}m ${seconds}s`,
  ].join("\n"));
}

function seedPaths(path: string): string[] {
  const parsed = JSON.parse(readFileSync(path, "utf8"));
  if (!Array.isArray(parsed.groups)) return [path];
  const base = dirname(path);
  return parsed.groups
    .filter((group: { status: string }) => group.status === "completed")
    .map((group: { file: string }) => {
      if (typeof group.file !== "string")
        throw new Error("Invalid index group file");
      const file = resolve(base, group.file);
      const rel = relative(base, file);
      if (
        isAbsolute(rel) ||
        rel === ".." ||
        rel.startsWith("../") ||
        rel.startsWith("..\\")
      ) {
        throw new Error(`Index file escapes output directory: ${group.file}`);
      }
      return file;
    });
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
