export const INVESTOR_SEED_PASSWORD = "investor123";

export const INVESTOR_ROLE_USERS = [
  {
    key: "investor_admin",
    roleName: "investor_admin",
    name: "Investor Admin",
    email: "investor.admin@z.shoes.com",
    phone: "01820000001",
  },
  {
    key: "investor_relations",
    roleName: "investor_relations",
    name: "Investor Relations Officer",
    email: "investor.relations@z.shoes.com",
    phone: "01820000002",
  },
  {
    key: "investor_analyst",
    roleName: "investor_analyst",
    name: "Investor Analyst",
    email: "investor.analyst@z.shoes.com",
    phone: "01820000003",
  },
  {
    key: "profit_manager",
    roleName: "profit_manager",
    name: "Profit Manager",
    email: "profit.manager@z.shoes.com",
    phone: "01820000004",
  },
  {
    key: "profit_approver",
    roleName: "profit_approver",
    name: "Profit Approver",
    email: "profit.approver@z.shoes.com",
    phone: "01820000005",
  },
  {
    key: "profit_poster",
    roleName: "profit_poster",
    name: "Profit Poster",
    email: "profit.poster@z.shoes.com",
    phone: "01820000006",
  },
  {
    key: "payout_manager",
    roleName: "payout_manager",
    name: "Payout Manager",
    email: "payout.manager@z.shoes.com",
    phone: "01820000007",
  },
  {
    key: "payout_approver",
    roleName: "payout_approver",
    name: "Payout Approver",
    email: "payout.approver@z.shoes.com",
    phone: "01820000008",
  },
  {
    key: "payout_payer",
    roleName: "payout_payer",
    name: "Payout Payer",
    email: "payout.payer@z.shoes.com",
    phone: "01820000009",
  },
] as const;

export const INVESTOR_PORTAL_USERS = [
  {
    key: "portal_yousuf",
    investorKey: "seed_001",
    name: "Yousuf Investor Portal",
    email: "investor.portal.yousuf@z.shoes.com",
    phone: "01821000001",
    status: "ACTIVE",
  },
  {
    key: "portal_mahin",
    investorKey: "seed_002",
    name: "Mahin Investor Portal",
    email: "investor.portal.mahin@z.shoes.com",
    phone: "01821000002",
    status: "ACTIVE",
  },
  {
    key: "portal_salehin",
    investorKey: "seed_003",
    name: "Salehin Investor Portal",
    email: "investor.portal.salehin@z.shoes.com",
    phone: "01821000003",
    status: "ACTIVE",
  },
  {
    key: "portal_nusrat",
    investorKey: "seed_004",
    name: "Nusrat Investor Portal",
    email: "investor.portal.nusrat@z.shoes.com",
    phone: "01821000004",
    status: "SUSPENDED",
  },
] as const;

export const INVESTOR_MASTER_RECORDS = [
  {
    key: "seed_001",
    code: "INV-SEED-001",
    name: "Yousuf Growth Capital",
    legalName: "Yousuf Growth Capital",
    email: "investor.seed001@z.shoes.com",
    phone: "01720000001",
    taxNumber: "TIN-INV-001",
    nationalIdNumber: "NID-INV-001",
    bankName: "DBBL",
    bankAccountName: "Yousuf Growth Capital",
    bankAccountNumber: "200000000001",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    beneficiaryVerified: true,
    note: "Seeded active verified investor with portal access.",
  },
  {
    key: "seed_002",
    code: "INV-SEED-002",
    name: "Mahin Retail Capital",
    legalName: "Mahin Retail Capital",
    email: "investor.seed002@z.shoes.com",
    phone: "01720000002",
    taxNumber: "TIN-INV-002",
    nationalIdNumber: "NID-INV-002",
    bankName: "Brac Bank",
    bankAccountName: "Mahin Retail Capital",
    bankAccountNumber: "200000000002",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    beneficiaryVerified: true,
    note: "Seeded active verified investor with portal access.",
  },
  {
    key: "seed_003",
    code: "INV-SEED-003",
    name: "Salehin Ecommerce Partners",
    legalName: "Salehin Ecommerce Partners",
    email: "investor.seed003@z.shoes.com",
    phone: "01720000003",
    taxNumber: "TIN-INV-003",
    nationalIdNumber: "NID-INV-003",
    bankName: "City Bank",
    bankAccountName: "Salehin Ecommerce Partners",
    bankAccountNumber: "200000000003",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    beneficiaryVerified: true,
    note: "Seeded active verified investor with portal access.",
  },
  {
    key: "seed_004",
    code: "INV-SEED-004",
    name: "Nusrat Pending Capital",
    legalName: "Nusrat Pending Capital",
    email: "investor.seed004@z.shoes.com",
    phone: "01720000004",
    taxNumber: "TIN-INV-004",
    nationalIdNumber: "NID-INV-004",
    bankName: "Eastern Bank",
    bankAccountName: "Nusrat Pending Capital",
    bankAccountNumber: "200000000004",
    status: "ACTIVE",
    kycStatus: "PENDING",
    beneficiaryVerified: false,
    note: "Seeded pending KYC investor for exception/filter testing.",
  },
  {
    key: "seed_005",
    code: "INV-SEED-005",
    name: "Arafat Review Holdings",
    legalName: "Arafat Review Holdings",
    email: "investor.seed005@z.shoes.com",
    phone: "01720000005",
    taxNumber: "TIN-INV-005",
    nationalIdNumber: "NID-INV-005",
    bankName: "Prime Bank",
    bankAccountName: "Arafat Review Holdings",
    bankAccountNumber: "200000000005",
    status: "ACTIVE",
    kycStatus: "UNDER_REVIEW",
    beneficiaryVerified: false,
    note: "Seeded KYC under-review investor.",
  },
  {
    key: "seed_006",
    code: "INV-SEED-006",
    name: "Rafi Rejected Capital",
    legalName: "Rafi Rejected Capital",
    email: "investor.seed006@z.shoes.com",
    phone: "01720000006",
    taxNumber: "TIN-INV-006",
    nationalIdNumber: "NID-INV-006",
    bankName: "Mutual Trust Bank",
    bankAccountName: "Rafi Rejected Capital",
    bankAccountNumber: "200000000006",
    status: "INACTIVE",
    kycStatus: "REJECTED",
    beneficiaryVerified: false,
    note: "Seeded rejected KYC investor.",
  },
  {
    key: "seed_007",
    code: "INV-SEED-007",
    name: "Samira Suspended Ventures",
    legalName: "Samira Suspended Ventures",
    email: "investor.seed007@z.shoes.com",
    phone: "01720000007",
    taxNumber: "TIN-INV-007",
    nationalIdNumber: "NID-INV-007",
    bankName: "Bank Asia",
    bankAccountName: "Samira Suspended Ventures",
    bankAccountNumber: "200000000007",
    status: "SUSPENDED",
    kycStatus: "VERIFIED",
    beneficiaryVerified: true,
    note: "Seeded suspended investor for governance testing.",
  },
  {
    key: "seed_008",
    code: "INV-SEED-008",
    name: "Tanvir Inactive Fund",
    legalName: "Tanvir Inactive Fund",
    email: "investor.seed008@z.shoes.com",
    phone: "01720000008",
    taxNumber: "TIN-INV-008",
    nationalIdNumber: "NID-INV-008",
    bankName: "IFIC Bank",
    bankAccountName: "Tanvir Inactive Fund",
    bankAccountNumber: "200000000008",
    status: "INACTIVE",
    kycStatus: "VERIFIED",
    beneficiaryVerified: true,
    note: "Seeded inactive verified investor.",
  },
  {
    key: "seed_009",
    code: "INV-SEED-009",
    name: "Farhan No Portal Capital",
    legalName: "Farhan No Portal Capital",
    email: "investor.seed009@z.shoes.com",
    phone: "01720000009",
    taxNumber: "TIN-INV-009",
    nationalIdNumber: "NID-INV-009",
    bankName: "Standard Chartered",
    bankAccountName: "Farhan No Portal Capital",
    bankAccountNumber: "200000000009",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    beneficiaryVerified: true,
    note: "Seeded active investor without portal access.",
  },
  {
    key: "seed_010",
    code: "INV-SEED-010",
    name: "Jannat Unverified Beneficiary",
    legalName: "Jannat Unverified Beneficiary",
    email: "investor.seed010@z.shoes.com",
    phone: "01720000010",
    taxNumber: "TIN-INV-010",
    nationalIdNumber: "NID-INV-010",
    bankName: "NCC Bank",
    bankAccountName: "Jannat Unverified Beneficiary",
    bankAccountNumber: "200000000010",
    status: "ACTIVE",
    kycStatus: "VERIFIED",
    beneficiaryVerified: false,
    note: "Seeded verified KYC investor with unverified beneficiary for payout blocking tests.",
  },
] as const;

export const INVESTOR_SEED_VARIANT_SKUS = [
  "SCM-BOOT-BLK-42",
  "SCM-CARTON-MED",
  "SCM-POLY-L",
  "SCM-SCAN-USB",
  "SCM-PRINTER-4IN",
  "SCM-TAB-8IN",
] as const;
