export const SCM_SEED_PASSWORD = "scm123";

export const SCM_ROLE_USERS = [
  {
    key: "scm_admin",
    roleName: "scm_admin",
    name: "SCM Admin",
    email: "scm.admin@z.shoes.com",
    phone: "01810000001",
    warehouseCode: "WH-HQ",
  },
  {
    key: "procurement_manager",
    roleName: "procurement_manager",
    name: "Procurement Manager",
    email: "procurement.manager@z.shoes.com",
    phone: "01810000002",
    warehouseCode: "WH-HQ",
  },
  {
    key: "procurement_requestor",
    roleName: "procurement_requestor",
    name: "Procurement Requestor",
    email: "procurement.requestor@z.shoes.com",
    phone: "01810000003",
    warehouseCode: "WH-HQ",
  },
  {
    key: "warehouse_receiver",
    roleName: "warehouse_receiver",
    name: "Warehouse Receiver",
    email: "warehouse.receiver@z.shoes.com",
    phone: "01810000004",
    warehouseCode: "WH-HQ",
  },
  {
    key: "finance_focal",
    roleName: "finance_focal",
    name: "Finance Focal",
    email: "finance.focal@z.shoes.com",
    phone: "01810000005",
    warehouseCode: "WH-HQ",
  },
  {
    key: "ap_manager",
    roleName: "ap_manager",
    name: "AP Manager",
    email: "ap.manager@z.shoes.com",
    phone: "01810000006",
    warehouseCode: "WH-HQ",
  },
  {
    key: "procurement_committee",
    roleName: "procurement_committee",
    name: "Procurement Committee",
    email: "procurement.committee@z.shoes.com",
    phone: "01810000007",
    warehouseCode: "WH-HQ",
  },
  {
    key: "final_approver",
    roleName: "final_approver",
    name: "Final Approver",
    email: "final.approver@z.shoes.com",
    phone: "01810000008",
    warehouseCode: "WH-HQ",
  },
  {
    key: "warehouse_transfer_manager",
    roleName: "warehouse_transfer_manager",
    name: "Warehouse Transfer Manager",
    email: "warehouse.transfer@z.shoes.com",
    phone: "01810000009",
    warehouseCode: "WH-CTG",
  },
  {
    key: "replenishment_planner",
    roleName: "replenishment_planner",
    name: "Replenishment Planner",
    email: "replenishment.planner@z.shoes.com",
    phone: "01810000010",
    warehouseCode: "WH-CTG",
  },
  {
    key: "supplier_return_manager",
    roleName: "supplier_return_manager",
    name: "Supplier Return Manager",
    email: "supplier.return@z.shoes.com",
    phone: "01810000011",
    warehouseCode: "WH-SYL",
  },
  {
    key: "sla_manager",
    roleName: "sla_manager",
    name: "SLA Manager",
    email: "sla.manager@z.shoes.com",
    phone: "01810000012",
    warehouseCode: "WH-HQ",
  },
] as const;

export const SCM_WAREHOUSES = [
  {
    key: "hq",
    code: "WH-HQ",
    name: "Head Office Central Warehouse",
    division: "Dhaka",
    district: "Dhaka",
    area: "Tejgaon",
    latitude: 23.7639,
    longitude: 90.3908,
    isDefault: true,
  },
  {
    key: "ctg",
    code: "WH-CTG",
    name: "Chattogram Distribution Hub",
    division: "Chattogram",
    district: "Chattogram",
    area: "Agrabad",
    latitude: 22.3331,
    longitude: 91.8337,
    isDefault: false,
  },
  {
    key: "syl",
    code: "WH-SYL",
    name: "Sylhet Store Support Warehouse",
    division: "Sylhet",
    district: "Sylhet",
    area: "Amberkhana",
    latitude: 24.8949,
    longitude: 91.8687,
    isDefault: false,
  },
  {
    key: "khulna",
    code: "WH-KHL",
    name: "Khulna Regional Stock Point",
    division: "Khulna",
    district: "Khulna",
    area: "Sonadanga",
    latitude: 22.8456,
    longitude: 89.5403,
    isDefault: false,
  },
] as const;

export const SCM_CATEGORY_MASTERS = [
  { name: "Safety Footwear", slug: "scm-safety-footwear" },
  { name: "Packaging Materials", slug: "scm-packaging-materials" },
  { name: "Store Fixtures", slug: "scm-store-fixtures" },
  { name: "IT Equipment", slug: "scm-it-equipment" },
] as const;

export const SCM_BRANDS = [
  { name: "StridePro", slug: "stridepro" },
  { name: "PackRight", slug: "packright" },
  { name: "RackLine", slug: "rackline" },
  { name: "TekCore", slug: "tekcore" },
] as const;

export const SCM_PRODUCT_VARIANTS = [
  {
    key: "safety_boot_black_42",
    categorySlug: "scm-safety-footwear",
    brandSlug: "stridepro",
    productName: "Safety Boot Black",
    sku: "SCM-BOOT-BLK-42",
    price: "4200",
    costPrice: "2950",
    lowStockThreshold: 12,
    inventoryItemClass: "CONSUMABLE",
    requiresAssetTag: false,
    options: { size: "42", color: "Black" },
  },
  {
    key: "safety_boot_black_43",
    categorySlug: "scm-safety-footwear",
    brandSlug: "stridepro",
    productName: "Safety Boot Black",
    sku: "SCM-BOOT-BLK-43",
    price: "4200",
    costPrice: "2950",
    lowStockThreshold: 12,
    inventoryItemClass: "CONSUMABLE",
    requiresAssetTag: false,
    options: { size: "43", color: "Black" },
  },
  {
    key: "hi_vis_vest_l",
    categorySlug: "scm-safety-footwear",
    brandSlug: "stridepro",
    productName: "Hi-Vis Warehouse Vest",
    sku: "SCM-VEST-HIVIS-L",
    price: "850",
    costPrice: "520",
    lowStockThreshold: 20,
    inventoryItemClass: "CONSUMABLE",
    requiresAssetTag: false,
    options: { size: "L", color: "Neon Yellow" },
  },
  {
    key: "corrugated_carton_m",
    categorySlug: "scm-packaging-materials",
    brandSlug: "packright",
    productName: "Corrugated Carton Medium",
    sku: "SCM-CARTON-MED",
    price: "48",
    costPrice: "31",
    lowStockThreshold: 300,
    inventoryItemClass: "CONSUMABLE",
    requiresAssetTag: false,
    options: { size: "Medium", ply: "5" },
  },
  {
    key: "courier_polybag_l",
    categorySlug: "scm-packaging-materials",
    brandSlug: "packright",
    productName: "Courier Polybag Large",
    sku: "SCM-POLY-L",
    price: "12",
    costPrice: "7",
    lowStockThreshold: 500,
    inventoryItemClass: "CONSUMABLE",
    requiresAssetTag: false,
    options: { size: "Large", gauge: "80" },
  },
  {
    key: "fragile_label_roll",
    categorySlug: "scm-packaging-materials",
    brandSlug: "packright",
    productName: "Fragile Label Roll",
    sku: "SCM-LABEL-FRAGILE",
    price: "180",
    costPrice: "110",
    lowStockThreshold: 40,
    inventoryItemClass: "CONSUMABLE",
    requiresAssetTag: false,
    options: { type: "Sticker", roll: "500 pcs" },
  },
  {
    key: "steel_rack_5tier",
    categorySlug: "scm-store-fixtures",
    brandSlug: "rackline",
    productName: "Steel Rack 5 Tier",
    sku: "SCM-RACK-5TIER",
    price: "18500",
    costPrice: "13900",
    lowStockThreshold: 3,
    inventoryItemClass: "PERMANENT",
    requiresAssetTag: true,
    options: { level: "5", finish: "Powder Coat" },
  },
  {
    key: "barcode_scanner_usb",
    categorySlug: "scm-it-equipment",
    brandSlug: "tekcore",
    productName: "USB Barcode Scanner",
    sku: "SCM-SCAN-USB",
    price: "5900",
    costPrice: "4300",
    lowStockThreshold: 6,
    inventoryItemClass: "PERMANENT",
    requiresAssetTag: true,
    options: { connectivity: "USB", type: "Laser" },
  },
  {
    key: "thermal_printer_4in",
    categorySlug: "scm-it-equipment",
    brandSlug: "tekcore",
    productName: "Thermal Label Printer 4 Inch",
    sku: "SCM-PRINTER-4IN",
    price: "14500",
    costPrice: "11100",
    lowStockThreshold: 4,
    inventoryItemClass: "PERMANENT",
    requiresAssetTag: true,
    options: { width: "4 inch", connectivity: "USB" },
  },
  {
    key: "tablet_ops_8in",
    categorySlug: "scm-it-equipment",
    brandSlug: "tekcore",
    productName: "Operations Tablet 8 Inch",
    sku: "SCM-TAB-8IN",
    price: "22000",
    costPrice: "17800",
    lowStockThreshold: 4,
    inventoryItemClass: "PERMANENT",
    requiresAssetTag: true,
    options: { display: "8 inch", memory: "64GB" },
  },
  {
    key: "hand_pallet_truck",
    categorySlug: "scm-store-fixtures",
    brandSlug: "rackline",
    productName: "Hand Pallet Truck",
    sku: "SCM-PALLET-HAND",
    price: "32000",
    costPrice: "25800",
    lowStockThreshold: 2,
    inventoryItemClass: "PERMANENT",
    requiresAssetTag: true,
    options: { capacity: "2 Ton", fork: "Standard" },
  },
  {
    key: "cctv_dome_cam",
    categorySlug: "scm-it-equipment",
    brandSlug: "tekcore",
    productName: "Warehouse CCTV Dome Camera",
    sku: "SCM-CCTV-DOME",
    price: "4800",
    costPrice: "3550",
    lowStockThreshold: 6,
    inventoryItemClass: "PERMANENT",
    requiresAssetTag: true,
    options: { resolution: "2MP", type: "Dome" },
  },
] as const;

export const SCM_SUPPLIERS = [
  {
    key: "alpha_safety",
    code: "SUP-SCM-001",
    name: "Alpha Safety Gear Ltd",
    companyType: "LIMITED_COMPANY",
    contactName: "Imran Hossain",
    email: "alpha.safety@vendor.test",
    phone: "01911000001",
    city: "Dhaka",
    leadTimeDays: 7,
    paymentTermsDays: 30,
    taxNumber: "TIN-SCM-001",
    categories: ["APPAREL"],
    portal: true,
  },
  {
    key: "packmate",
    code: "SUP-SCM-002",
    name: "PackMate Solutions",
    companyType: "LIMITED_COMPANY",
    contactName: "Sadia Rahman",
    email: "packmate@vendor.test",
    phone: "01911000002",
    city: "Gazipur",
    leadTimeDays: 5,
    paymentTermsDays: 21,
    taxNumber: "TIN-SCM-002",
    categories: ["PACKAGING"],
    portal: true,
  },
  {
    key: "tekbridge",
    code: "SUP-SCM-003",
    name: "TekBridge Systems",
    companyType: "LIMITED_COMPANY",
    contactName: "Tanvir Ahmed",
    email: "tekbridge@vendor.test",
    phone: "01911000003",
    city: "Dhaka",
    leadTimeDays: 10,
    paymentTermsDays: 30,
    taxNumber: "TIN-SCM-003",
    categories: ["IT_EQUIPMENT"],
    portal: true,
  },
  {
    key: "rackworks",
    code: "SUP-SCM-004",
    name: "RackWorks Engineering",
    companyType: "PROPRIETOR",
    contactName: "Mokhlesur Rahman",
    email: "rackworks@vendor.test",
    phone: "01911000004",
    city: "Chattogram",
    leadTimeDays: 14,
    paymentTermsDays: 30,
    taxNumber: "TIN-SCM-004",
    categories: ["FURNITURE", "FACILITY_MAINTENANCE"],
    portal: true,
  },
  {
    key: "swiftlogix",
    code: "SUP-SCM-005",
    name: "SwiftLogix Services",
    companyType: "LIMITED_COMPANY",
    contactName: "Mahmudul Karim",
    email: "swiftlogix@vendor.test",
    phone: "01911000005",
    city: "Dhaka",
    leadTimeDays: 3,
    paymentTermsDays: 15,
    taxNumber: "TIN-SCM-005",
    categories: ["LOGISTICS_SERVICES"],
    portal: false,
  },
  {
    key: "officebay",
    code: "SUP-SCM-006",
    name: "OfficeBay Supplies",
    companyType: "PROPRIETOR",
    contactName: "Ayesha Noor",
    email: "officebay@vendor.test",
    phone: "01911000006",
    city: "Dhaka",
    leadTimeDays: 4,
    paymentTermsDays: 20,
    taxNumber: "TIN-SCM-006",
    categories: ["OFFICE_SUPPLIES"],
    portal: false,
  },
  {
    key: "printcraft",
    code: "SUP-SCM-007",
    name: "PrintCraft Media",
    companyType: "LIMITED_COMPANY",
    contactName: "Asif Shahriar",
    email: "printcraft@vendor.test",
    phone: "01911000007",
    city: "Narayanganj",
    leadTimeDays: 6,
    paymentTermsDays: 25,
    taxNumber: "TIN-SCM-007",
    categories: ["PRINTING", "PACKAGING"],
    portal: false,
  },
  {
    key: "facility_pro",
    code: "SUP-SCM-008",
    name: "Facility Pro BD",
    companyType: "PROPRIETOR",
    contactName: "Khaled Hasan",
    email: "facilitypro@vendor.test",
    phone: "01911000008",
    city: "Sylhet",
    leadTimeDays: 8,
    paymentTermsDays: 20,
    taxNumber: "TIN-SCM-008",
    categories: ["FACILITY_MAINTENANCE", "GENERAL_SERVICES"],
    portal: false,
  },
  {
    key: "greenpack",
    code: "SUP-SCM-009",
    name: "GreenPack Bangladesh",
    companyType: "LIMITED_COMPANY",
    contactName: "Sharmin Akter",
    email: "greenpack@vendor.test",
    phone: "01911000009",
    city: "Khulna",
    leadTimeDays: 5,
    paymentTermsDays: 18,
    taxNumber: "TIN-SCM-009",
    categories: ["PACKAGING"],
    portal: false,
  },
  {
    key: "bytefield",
    code: "SUP-SCM-010",
    name: "ByteField Devices",
    companyType: "LIMITED_COMPANY",
    contactName: "Fahim Yasin",
    email: "bytefield@vendor.test",
    phone: "01911000010",
    city: "Dhaka",
    leadTimeDays: 9,
    paymentTermsDays: 30,
    taxNumber: "TIN-SCM-010",
    categories: ["IT_EQUIPMENT"],
    portal: false,
  },
  {
    key: "safetyhub",
    code: "SUP-SCM-011",
    name: "SafetyHub Traders",
    companyType: "PROPRIETOR",
    contactName: "Rasel Uddin",
    email: "safetyhub@vendor.test",
    phone: "01911000011",
    city: "Rajshahi",
    leadTimeDays: 6,
    paymentTermsDays: 21,
    taxNumber: "TIN-SCM-011",
    categories: ["APPAREL", "GENERAL_SERVICES"],
    portal: false,
  },
  {
    key: "metrostorage",
    code: "SUP-SCM-012",
    name: "Metro Storage Solutions",
    companyType: "LIMITED_COMPANY",
    contactName: "Nusrat Jahan",
    email: "metrostorage@vendor.test",
    phone: "01911000012",
    city: "Dhaka",
    leadTimeDays: 12,
    paymentTermsDays: 30,
    taxNumber: "TIN-SCM-012",
    categories: ["FURNITURE"],
    portal: false,
  },
] as const;
